services:
  - type: web
    name: apple-weight-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 300"
    envVars:
      - key: YOLO_MODEL_PATH
        value: assets/resources/yolo9-best.pt
      - key: KNN_MODEL_PATH
        value: assets/resources/knn_model.sav
      - key: DATABASE_URL
        value: sqlite:///./apple_detection.db
      - key: VIDEO_UPLOAD_DIR
        value: assets/uploaded/videos
      - key: PICTURE_UPLOAD_DIR
        value: assets/uploaded/pictures
      - key: VIDEO_OUTPUT_DIR
        value: assets/output/videos
      - key: PICTURE_OUTPUT_DIR
        value: assets/output/pictures